# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_zero = QtWidgets.QLabel(self.centralwidget)
        self.label_zero.setGeometry(QtCore.QRect(60, 30, 571, 161))
        self.label_zero.setWordWrap(True)
        self.label_zero.setObjectName("label_zero")
        self.label_one = QtWidgets.QLabel(self.centralwidget)
        self.label_one.setGeometry(QtCore.QRect(60, 210, 571, 161))
        self.label_one.setWordWrap(True)
        self.label_one.setObjectName("label_one")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 100, 21, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 280, 21, 17))
        self.label_2.setObjectName("label_2")
        self.label_couplet = QtWidgets.QLabel(self.centralwidget)
        self.label_couplet.setGeometry(QtCore.QRect(20, 10, 431, 17))
        self.label_couplet.setObjectName("label_couplet")
        self.comboBox_couplet = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_couplet.setGeometry(QtCore.QRect(690, 60, 191, 25))
        self.comboBox_couplet.setObjectName("comboBox_couplet")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(690, 30, 131, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(690, 110, 141, 17))
        self.label_4.setObjectName("label_4")
        self.comboBox_species = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_species.setGeometry(QtCore.QRect(690, 140, 191, 25))
        self.comboBox_species.setObjectName("comboBox_species")
        self.pushButton_jump = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_jump.setGeometry(QtCore.QRect(690, 200, 191, 91))
        self.pushButton_jump.setObjectName("pushButton_jump")
        self.label_species = QtWidgets.QLabel(self.centralwidget)
        self.label_species.setGeometry(QtCore.QRect(20, 410, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_species.setFont(font)
        self.label_species.setObjectName("label_species")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(20, 450, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 500, 131, 21))
        self.label_6.setObjectName("label_6")
        self.comboBox_status = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_status.setGeometry(QtCore.QRect(150, 500, 71, 25))
        self.comboBox_status.setObjectName("comboBox_status")
        self.pushButton_change = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_change.setGeometry(QtCore.QRect(20, 550, 201, 81))
        self.pushButton_change.setObjectName("pushButton_change")
        self.pushButton_nextCouplet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_nextCouplet.setGeometry(QtCore.QRect(720, 460, 161, 81))
        self.pushButton_nextCouplet.setObjectName("pushButton_nextCouplet")
        self.pushButton_nextSpecies = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_nextSpecies.setGeometry(QtCore.QRect(720, 550, 161, 81))
        self.pushButton_nextSpecies.setObjectName("pushButton_nextSpecies")
        self.pushButton_previousSpecies = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_previousSpecies.setGeometry(QtCore.QRect(580, 550, 131, 81))
        self.pushButton_previousSpecies.setObjectName("pushButton_previousSpecies")
        self.pushButton_previousCouplet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_previousCouplet.setGeometry(QtCore.QRect(580, 460, 131, 81))
        self.pushButton_previousCouplet.setObjectName("pushButton_previousCouplet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_zero.setText(_translate("MainWindow", "TextLabel"))
        self.label_one.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "0."))
        self.label_2.setText(_translate("MainWindow", "1."))
        self.label_couplet.setText(_translate("MainWindow", "Couplet name:"))
        self.label_3.setText(_translate("MainWindow", "Select couplet:"))
        self.label_4.setText(_translate("MainWindow", "Select species:"))
        self.pushButton_jump.setText(_translate("MainWindow", "Jump!"))
        self.label_species.setText(_translate("MainWindow", "Species name:"))
        self.label_status.setText(_translate("MainWindow", "Current status: "))
        self.label_6.setText(_translate("MainWindow", "Change status to:"))
        self.pushButton_change.setText(_translate("MainWindow", "Change!"))
        self.pushButton_nextCouplet.setText(_translate("MainWindow", "Next couplet"))
        self.pushButton_nextSpecies.setText(_translate("MainWindow", "Next species"))
        self.pushButton_previousSpecies.setText(_translate("MainWindow", "Previous species"))
        self.pushButton_previousCouplet.setText(_translate("MainWindow", "Previous couplet"))

